#
# See documentation for the options here
# https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
#

# Staging and publishing profile for yourproject-website.git:
staging:
  profile: ~
  whoami:  asf-staging