#
# See documentation for the options here
# https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
#

# Staging and publishing profile for yourproject-website.git:
staging:
  profile: ~
  whoami:  asf-staging

github:
  description: "Repository used to build the Apache James website"
  homepage: https://james.apache.org/
  labels:
    - mail
    - server
    - imap
    - smtp
    - jmap
notifications:
  commits:      notifications@james.apache.org
  issues:       notifications@james.apache.org
  pullrequests: notifications@james.apache.org
  jira_options: link label worklog
