site:
  title: Apache James
  url: https://james.apache.org/
  start_page: main::index.adoc
content:
  sources:
  - url: https://gitbox.apache.org/repos/asf/james-hupa.git
    branches: master
    start_path: docs
  - url: https://gitbox.apache.org/repos/asf/james-jdkim.git
    branches: master
    start_path: docs
  - url: https://gitbox.apache.org/repos/asf/james-jsieve.git
    branches: master
    start_path: docs
  - url: https://gitbox.apache.org/repos/asf/james-jspf.git
    branches: master
    start_path: docs
  - url: https://gitbox.apache.org/repos/asf/james-mime4j.git
    branches: master
    start_path: docs
  - url: https://gitbox.apache.org/repos/asf/james-project.git
    branches: master
    start_path: docs
  - url: https://gitbox.apache.org/repos/asf/james-postage.git
    branches: master
    start_path: docs
  - url: ./../
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: ./../antora-ui/build/ui-bundle.zip
    # start_path: ui-bundle
runtime:
  fetch: true
