site:
  title: Apache James
  url: https://james.apache.org/
  start_page: main::index.adoc
content:
  sources:
  - url: https://gitbox.apache.org/repos/asf/james-project.git
    branches: HEAD
    start_path: docs
  # - url: https://gitbox.apache.org/repos/asf/james-jsieve.git
  #   branches: HEAD
  #   start_path: docs
ui:
  bundle:
    url: ./../ui-bundle/build/distributions/ui-bundle.zip
    start_path: ui-bundle
runtime:
  fetch: true
