site:
  title: Apache James
  url: https://james.apache.org/
  start_page: james-site::homepage.adoc
content:
  sources:
  - url: https://gitbox.apache.org/repos/asf/james-hupa.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: https://gitbox.apache.org/repos/asf/james-jdkim.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: https://gitbox.apache.org/repos/asf/james-jsieve.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: https://gitbox.apache.org/repos/asf/james-jspf.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: https://gitbox.apache.org/repos/asf/james-mime4j.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: https://gitbox.apache.org/repos/asf/james-project.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: https://gitbox.apache.org/repos/asf/james-postage.git
    branches: master
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
  - url: ./../
    branches: HEAD
    start_path: docs
    edit_url: '{web_url}/blob/{refname}/{path}'
ui:
  bundle:
    url: ./../antora-ui/build/ui-bundle.zip
    # start_path: ui-bundle
runtime:
  fetch: true
