runtime:
  cache_dir: ./.cache/antora
  fetch: true
site:
  title: Apache James
  url: https://james.apache.org/
  start_page: james-site::homepage.adoc
content:
  sources:
    - url: https://github.com/chibenwa/james-project.git
      branches: master
      start_path: docs
      edit_url: "{web_url}/blob/{refname}/{path}"
    - url: https://github.com/apache/james-project.git
      branches: 3.8.x
      start_path: docs
      edit_url: "{web_url}/blob/{refname}/{path}"
    - url: https://github.com/apache/james-project.git
      branches: 3.7.x
      start_path: docs
      edit_url: "{web_url}/blob/{refname}/{path}"
    - url: https://github.com/apache/james-project.git
      branches: 3.8.x
      start_path: server/apps/distributed-app/docs
      edit_url: "{web_url}/blob/{refname}/{path}"
    - url: https://github.com/apache/james-project.git
      branches: 3.7.x
      start_path: server/apps/distributed-app/docs
      edit_url: "{web_url}/blob/{refname}/{path}"
    - url: https://github.com/apache/james-project.git
      branches: master
      start_path: server/apps/distributed-app/docs
      edit_url: "{web_url}/blob/{refname}/{path}"
    - url: ./../
      branches: HEAD
      start_path: docs
      edit_url: "{web_url}/blob/{refname}/{path}"
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./ui-overrides
