= Apache James
:navtitle: Home

*Emails at the heart of your business logic.*

James stands for *Java Apache Mail Enterprise Server*!

It has a modular architecture based on a rich set of modern and efficient components which provides
at the end complete, stable, secure and extendable Mail Servers running on the JVM.

Create your own personal solution of emails treatment by assembling the components you need thanks
to the Inversion of Control mail platform offered, and go further customizing filtering and routing
rules using the James Mailet Container.

James is a living Open Source project - all developments and implementations are based on open
technical standards - and any function which is not already available can be developed!

== The James server

The James server wires together the different libraries composing James to provide running services.

From a technical point of view:

* Complete portability: 100% pure JVM (Java & Scala).
* Emailing protocols: SMTP, LMTP, POP3, IMAP, ManageSieve, JMAP.
* Mailet container: independent, extensible and pluggable email processing agents.
* Storage API: Mailbox API / Search API / User API.
* Storage implementations: Cassandra / PostgreSQL / HSQLDB / MySQL / OpenSearch...
* Administration: JMX / REST / Command line.

Your James server can also be used as a Mail Transfer Agent, by enabling only SMTP, or as an IMAP
Mail Delivery Agent.

Recent work of the Apache James project did lead to a James product that leverages a *distributed
mail server*, fully horizontally scalable, using storage technologies like Cassandra, OpenSearch,
RabbitMQ and object storage (S3/Swift).

* xref:james-project::index.adoc[*Apache James Server documentation*] - installation,
configuration, concepts, customization and development guides.
* xref:james-distributed-app::index.adoc[*Distributed James Server documentation*] - running the
horizontally scalable flavour of James.
* xref:download.adoc[Download page] - artifacts and sources for the James server and the James
libraries.

== The James libraries

Beyond the server, the Apache James project maintains a set of subprojects: standalone libraries
that can be plugged into any JVM mail application.

=== Mime4J

Apache James Mime4J provides a parser, `MimeStreamParser`, for e-mail message streams in plain
RFC-822 and MIME format. The parser uses a callback mechanism to report parsing events such as the
start of an entity header, the start of a body, etc. If you are familiar with the SAX XML parser
interface, you should have no problem getting started with Mime4J.

The parser only deals with the structure of the message stream - this is intentional, as it should
only provide the most basic functionality needed to build more complex parsers - but Mime4J does
include facilities to decode bodies and fields, and can build a tree representation of an e-mail
message. It has been designed to be extremely tolerant against messages violating the standards.

xref:mime4j::index.adoc[*Mime4J documentation*]

=== jSieve

jSieve is a Java implementation of the Sieve mail filtering language defined by RFC 5228. jSieve is
implemented as a language processor that can be plugged into any internet mail application to add
Sieve support.

Sieve is an extensible mail filtering language. Its limited expressiveness - no loops or variables,
no tests with side effects - allows user created scripts to be run safely on email servers. Sieve is
targeted at the final delivery phase, where an incoming email is transferred to a user's mailbox.

jSieve consists of two products: *Apache jSieve*, the Sieve library itself, and *Apache jSieve
Utilities*, which contains utility classes helpful when using Sieve but not considered sufficiently
core to be included in the main library.

xref:jsieve::index.adoc[*jSieve documentation*]

=== jSPF

The jSPF library is a pure Java SPF implementation, designed to match the SPF specifications. SPF,
also known as *Sender Policy Framework*, was designed to detect email spoofing: this is the solution
if you ever were tired of getting spam from yourself.

xref:jspf::index.adoc[*jSPF documentation*]

=== jDKIM

jDKIM is a DKIM - *DomainKeys Identified Mail* - implementation library written in Java. It provides
both verification and signing, and also provides Mailets for the Apache James project.

Its architecture is thought to handle multiple signatures with performance in mind: body hashing for
multiple signatures is computed concurrently in a single stream run.

xref:jdkim::index.adoc[*jDKIM documentation*]

== Join the community

Apache James Project is an Open Source all-volunteer project obtaining its strength from its
Community made of developers and users. All are welcome to the Community!

Have a look at xref:community.adoc[how to join the community], subscribe to the
xref:mailing-lists.adoc[mailing lists], and read the xref:contributing.adoc[contributing guide] to
submit your first patch. We also describe the xref:persona.adoc[people we build James for], and list
the xref:support.adoc[companies providing professional support].
